### ISSUE TITLE
Add Hall effect magnet holder to shuttle

### ISSUE THREAD

**Issue by TheSin-** [viesturz/tapchanger#12]
I'm going to attempt this as soon as I can run Fusion360 again. But I wanted to make a ticket so I remembered and I can check it off.

Once added the shuttle can print on its side and shouldn't require supports anymore.  I will test this theory once I mod the design to have the Hall effect pocket from the original Voron Tap, this should add the X end stop from the original design as well which would then be able to remove the XEndstop files from this project.

Of course this is all just theory ATM and I'll have to get the position perfectly matched and make sure I clear the other parts.

**Comment by viesturz** [comment]
Added, see the https://github.com/viesturz/tapchanger/tree/main/STL/Endstops
