### ISSUE TITLE
proprietary cad format

### ISSUE THREAD

**Issue by sirus20x6** [viesturz/tapchanger#13]
can we get the cad files as step as well? it would be nice to be able to use freecad to open the files and work on them

**Comment by viesturz** [comment]
Hi, will add step files later today.

**Comment by viesturz** [comment]
Added step files for plates and square rods, the round rods version needs a bit more work - I modified it to make square rods, will get back with that soon.

**Comment by alfskaar** [comment]
Can we have step files please.

**Comment by viesturz** [comment]
Added, let me know if this works, unfortunately the square and round rods are the same model. I'm looking for a way to add both to the same assembly without too much hacks. Let me know if you need the round rods version.

**Comment by alfskaar** [comment]
Thanks. Yes I will be using the "round rods" I see the CAD have square holes.

**Comment by alfskaar** [comment]
I wonder it whole have be easier if you made several STEP files as I’m  not really sure with one. ? For AFTERBURNER or Stealthburner

<img width="1626" alt="Screenshot 2023-10-26 at 23 01 34" src="https://github.com/viesturz/tapchanger/assets/31868161/95c244c5-e26b-4e87-adfe-42bcd2a1b04b">

**Comment by viesturz** [comment]
The cad now has no holes at all, but includes the hole shapes - substract the one you need.
