### ISSUE TITLE
BOM

### ISSUE THREAD

**Issue by alfskaar** [viesturz/tapchanger#15]
Update the BOM to reflect that there are 
Bearings 3x8x4 or 3x10x4 used depending on rods or pads
And flanged (3x10x4)

Update:
After taking a closer lock at the CAD flange bearings is used on the pad version so depending on which one you are building you may need one of this.
                  mm...
Bearings 3x8x4 
Bearings 3x10x4
Bearings 3x10x4 flanged (11.5)

Pinned belt Tapchanger
I have started to modify it since I'm building two double Y gantry Voron 2.4 one small one very big.
Like this. I need to use MG9H to make this work without altering the belt pathway on XY joint's

This should make it easier to take the belt on and off and get it at the exact same place.

Inspired by this video.
https://youtu.be/ZaqttrUeE4I?t=282

**Comment by viesturz** [comment]
Hi, Updated the BOMs. It would be best if  you can open a new bug for the Pinned Belt.
