### ISSUE TITLE
toolchanger.cfg Error

### ISSUE THREAD

**Issue by killgates1986** [viesturz/tapchanger#16]
im getting:
Option 't_command_restore_axis' is not valid in section 'toolchanger'
toolchanger installed as instructed on github. got the toolchanger.py in my extras on rpi.
[klippy (9).log](https://github.com/viesturz/tapchanger/files/13210346/klippy.9.log)

**Comment by viesturz** [comment]
This is caused by no tools areconfigured. Should go away once you have at least one tool.
I'm updating the code to avoid throwing the error without any tools.

**Comment by viesturz** [comment]
Change pushed.
