### ISSUE TITLE
New DragonBurner Cowling is missing 2 holes

### ISSUE THREAD

**Issue by repraph** [viesturz/tapchanger#17]
nice work.

are the two bottom holes on the new "hook on" dragonburner cowling missing on purpose?

**Comment by viesturz** [comment]
Good catch. That one is not updated. At this point I'm not sure if the hook on design is worth it.
I think the magnetic pins can work well with some tweaks.
I'm marking it as experimental for now. IE - feel free to print and test it, but further support is unclear.
