### ISSUE TITLE
Stealthburner Toolhead support for TapSensor is too weak

### ISSUE THREAD

**Issue by orotecluc** [viesturz/tapchanger#27]
Hi,
Iam trying the StealthBurner Square Rods version of  Tapchanger/STL/Toolheads/Stealthburner.
But everytime, the mount to where Ihave to put the Tap Sensor, breaks off.
Since I have no Fusion360 experience at all, wouldn't it be possible to give it a more sturdy top wall, in line with the mount on the Voron-Tap? 
I know, on Voron Tap, the stup is completly different, with a seperate peace to mount the sensor, and heavy side walls on both sides of the sensor, to make the mount more sturdy, but I think, with a thicker top layer on mount piece, we can have already a good result.
I tried doing a mockup in Tinkercad : 
- [https://i.imgur.com/PHsDbpf.png](Zoomin)
- [https://i.imgur.com/Zt0iHWP.png](full view) 
I know my 3D drawing skills are close to none

**Comment by viesturz** [comment]
Can you add a picture how exactly it breaks off?
Does it break during assembly? Or when printing?

**Comment by orotecluc** [comment]
It breaks OFF during assembly.
https://i.imgur.com/OW3rEFs.jpg

**Comment by orotecluc** [comment]
![20240219_135816.jpg](https://github.com/viesturz/tapchanger/assets/98692714/4f965e3c-d407-4b74-aac4-bf2c9fe7dc11)

The bridge detaches rally easaly, but i thank, if we kake the backpart of that bridge stronger, Luke in my tinkercatd try, everything Will keep hold

**Comment by viesturz** [comment]
Thanks, making a more robust version...

**Comment by viesturz** [comment]
There, added 2 mm of plastic, let me know if this works.

**Comment by orotecluc** [comment]
sorry, late out this evening. Testprinting right now.
Thanks for the fast response

**Comment by orotecluc** [comment]
Prints are great now, mounted complete Square-rod-toolhead. Just had some issues mounting the TAP sensor, BHCS6mm are a bit too long, it seems, and screw holes are really narrow. Double magnets are a great upgrade.
