### ISSUE TITLE
OMG... the new DB Cowling design.

### ISSUE THREAD

**Issue by walterwissmann** [viesturz/tapchanger#36]
The old one with the markers was a better design and his functionality was very good ;-)

**Comment by viesturz** [comment]
Thanks for the input. I agree the new ones are a bit fugly.
Moved away from main branch for now.

So there are two cahnges I'm trying to do with this:
- move the hook points further apart for better docked stability.
- allow for ~1mm tolerance in all directions.

Let me know if you have some ideas how to better get there.

**Comment by viesturz** [comment]
I sketched up an alternative. Kinda a middle ground between all form and all function.
Will test print and upload. 
Let me know if you have ideas.

![Screenshot 2024-03-11 205138](https://github.com/viesturz/tapchanger/assets/1640947/37cfebf8-41c5-47d9-a810-3f210f44a4d5)

**Comment by walterwissmann** [comment]
The look and feel of the old version with the markers has a high-quality and friendly appearance:

![grafik](https://github.com/viesturz/tapchanger/assets/42293697/2ddafc18-d8a3-4694-b273-39da89a1ed32)

Two things i have done per hand to have a super functionality: 

a. i have make the front holes a little bit greater, 6,5mm.

b. I cut the plastic spacers for the suspension bolts on the park mount a little conically so that the plastic remains behind the bolt and the Dragonburner doesn't bump into it.

This allows the cowling to slide easily over the screw into position. 

![grafik](https://github.com/viesturz/tapchanger/assets/42293697/2af5d2ff-1b07-4178-8999-8e25a0a32206)

BR
roerich_64 

p.s. we can discus via discord. i am also there ;-)
