### ISSUE TITLE
CAD for the new toolhead

### ISSUE THREAD

**Issue by nhchiu** [viesturz/tapchanger#41]
Do you have the CAD file for the new toolhead introduced in V4.1 available?

**Comment by viesturz** [comment]
https://github.com/viesturz/tapchanger/blob/main/Tapchanger/CAD/Tapchanger-All.step

**Comment by nhchiu** [comment]
> [`main`/Tapchanger/CAD/Tapchanger-All.step](https://github.com/viesturz/tapchanger/blob/main/Tapchanger/CAD/Tapchanger-All.step?rgh-link-date=2024-05-06T20%3A06%3A04Z)

@viesturz Sorry I mean the CAD file for this:
https://github.com/viesturz/tapchanger/blob/main/Tapchanger/STL/Toolheads/DragonBurner/HGX%20Gears/Front%20Dragon.stl

**Comment by viesturz** [comment]
Added https://github.com/viesturz/tapchanger/blob/main/Tapchanger/STL/Toolheads/DragonBurner/HGX%20Gears/CAD.step

**Comment by nhchiu** [comment]
@viesturz If you had taken CAD files from other projects to use in your design, 
please note where you took it from properly.

**Comment by viesturz** [comment]
See the credits in readme.md
Or let me know if you have specific concerns.

Viesturs

**Comment by nhchiu** [comment]
@viesturz Did you use the design from here? https://github.com/nhchiu/VoronMods/tree/main/Extruders%2FProtoXtruder

**Comment by viesturz** [comment]
Yes, that's right, updated the credits.
