### ISSUE TITLE
Shuttle issue below belts

### ISSUE THREAD

**Issue by vikwin** [viesturz/tapchanger#44]
I noticed that the non-aluminum shuttle warps a lot when it is attached to the linear rail. When looking for the cause, I saw that the smooth surfaces next to the belts are not in the same plane, but are offset. 
I noticed this with the “old” version from before 2024-05-08, but it is also the case with the newer version.
![shuttle_issue](https://github.com/viesturz/tapchanger/assets/6973946/4ef5a598-d6c0-4bef-a827-67fdd372883d)

Edit:
For the aluminum version, the same seems to apply for the surface between the belts - it's offset to the surfaces below and on top of the belts. That's not the case for the non-aluminum version, which makes me think it hasn't been made that way on purpose. I could be wrong though...

**Comment by viesturz** [comment]
Hmm, indeed. Let me try to fix it.
The belt groove profile was imported from previous iteration, perhaps
something is messed up there.

This aside, there should be some deformation from bolting down the shuttle
from the belt compression. You should be able to compensate by adjusting
the bottom screws on each toolhead.

**Comment by viesturz** [comment]
There fixed. Thanks again for noticing this.

Fusion 360 magic - that extra padding was meant for the central area to slot into the rail carriage and F360 managed to move it to a diffrent surface though some edits. 
Removing it altogether. The central area would interfere if you use a shuttle keeper.

**Comment by vikwin** [comment]
Thanks for your fast reaction, I really appreciate your efforts for the community with tapchanger!
Do you have any plans on removing the central area padding for the aluminum version as well?

**Comment by viesturz** [comment]
I added separate keeper optimized versions instead.
